export const cars = [
  {
    make: "Seat",
    models: [
      "Alhambra",
      "Altea",
      "Altea XL",
      "Arosa",
      "Cordoba",
      "Exeo",
      "Ibiza",
      "Ibiza ST",
      "Exeo ST",
      "Leon",
      "Leon ST",
      "Inca",
      "Mii",
      "Toledo",
    ],
  },
  {
    make: "Renault",
    models: [
      "Captur",
      "Clio",
      "Clio Grandtour",
      "Espace",
      "Express",
      "Fluence",
      "Grand Espace",
      "Grand Modus",
      "Grand Scenic",
      "Kadjar",
      "Kangoo",
      "Koleos",
      "Laguna",
      "Latitude",
      "Mascott",
      "Megane",
      "Scenic",
      "Talisman",
      "Thalia",
      "Twingo",
      "Wind",
      "Zoe",
    ],
  },
  {
    make: "Peugeot",
    models: [
      "1007",
      "107",
      "106",
      "108",
      "2008",
      "205",
      "206",
      "207",
      "306",
      "307",
      "308",
      "309",
      "4007",
      "4008",
      "405",
      "406",
      "407",
      "5008",
      "508",
      "605",
      "806",
      "607",
      "807",
      "Bipper",
      "RCZ",
    ],
  },
  {
    make: "Dacia",
    models: ["Dokker", "Duster", "Lodgy", "Logan", "Logan MCV", "Logan Van", "Sandero", "Solenza"],
  },
  {
    make: "Citroen",
    models: [
      "Berlingo",
      "C-Crosser",
      "C-Elissee",
      "C-Zero",
      "C1",
      "C2",
      "C3",
      "C4",
      "C5",
      "C6",
      "C8",
      "DS3",
      "DS4",
      "DS5",
      "Evasion",
      "Jumper",
      "Jumpy",
      "Saxo",
      "Nemo",
      "Xantia",
      "Xsara",
    ],
  },
  {
    make: "Opel",
    models: [
      "Agila",
      "Ampera",
      "Antara",
      "Astra",
      "Calibra",
      "Campo",
      "Cascada",
      "Corsa",
      "Frontera",
      "Insignia",
      "Kadett",
      "Meriva",
      "Mokka",
      "Movano",
      "Omega",
      "Signum",
      "Vectra",
      "Vivaro",
      "Zafira",
    ],
  },
  {
    make: "Alfa Romeo",
    models: [
      "145",
      "146",
      "147",
      "155",
      "156",
      "159",
      "164",
      "166",
      "4C",
      "Brera",
      "GTV",
      "MiTo",
      "Crosswagon",
      "Spider",
      "GT",
      "Giulietta",
      "Giulia",
    ],
  },
  {
    make: "Skoda",
    models: [
      "Favorit",
      "Felicia",
      "Citigo",
      "Fabia",
      "Felicia Combi",
      "Octavia",
      "Roomster",
      "Yeti",
      "Rapid",
      "Superb",
    ],
  },
  {
    make: "Chevrolet",
    models: [
      "Alero",
      "Aveo",
      "Camaro",
      "Captiva",
      "Corvette",
      "Cruze",
      "Epica",
      "Equinox",
      "Evanda",
      "HHR",
      "Kalos",
      "Lacetti",
      "Lumina",
      "Malibu",
      "Matiz",
      "Monte Carlo",
      "Nubira",
      "Orlando",
      "Spark",
      "Suburban",
      "Tacuma",
      "Tahoe",
      "Trax",
    ],
  },
  {
    make: "Porsche",
    models: [
      "911 Carrera",
      "911 Carrera Cabrio",
      "911 Targa",
      "911 Turbo",
      "924",
      "944",
      "997",
      "Boxster",
      "Cayenne",
      "Cayman",
      "Macan",
      "Panamera",
    ],
  },
  {
    make: "Honda",
    models: [
      "Accord",
      "City",
      "Civic",
      "CR-V",
      "CR-X",
      "CR-Z",
      "FR-V",
      "HR-V",
      "Insight",
      "Integra",
      "Jazz",
      "Legend",
      "Prelude",
    ],
  },
  {
    make: "Subaru",
    models: [
      "BRZ",
      "Forester",
      "Impreza",
      "Justy",
      "Legacy",
      "Levorg",
      "Outback",
      "SVX",
      "Tribeca",
      "XV",
    ],
  },
  {
    make: "Mazda",
    models: [
      "121",
      "2",
      "3",
      "323",
      "5",
      "6",
      "626",
      "B-Fighter",
      "B2500",
      "BT",
      "CX-3",
      "CX-5",
      "CX-7",
      "CX-9",
      "Demio",
      "MPV",
      "MX-3",
      "MX-5",
      "MX-6",
      "Premacy",
      "RX-7",
      "RX-8",
      "Xedox 6",
    ],
  },
  {
    make: "Mitsubishi",
    models: [
      "3000 GT",
      "ASX",
      "Carisma",
      "Colt",
      "Colt CC",
      "Eclipse",
      "Fuso canter",
      "Galant",
      "Grandis",
      "L200",
      "L300",
      "Lancer",
      "Outlander",
      "Pajero",
      "Space Star",
    ],
  },
  {
    make: "Lexus",
    models: [
      "CT",
      "GS",
      "GS 300",
      "GX",
      "IS",
      "IS 200",
      "IS 250 C",
      "IS-F",
      "LS",
      "LX",
      "NX",
      "RC F",
      "RX",
      "RX 300",
      "RX 400h",
      "RX 450h",
      "SC 430",
    ],
  },
  {
    make: "Toyota",
    models: [
      "4-Runner",
      "Auris",
      "Avensis",
      "Aygo",
      "Camry",
      "Carina",
      "Celica",
      "Corolla",
      "FJ Cruiser",
      "GT86",
      "Hiace",
      "Hiace Van",
      "Highlander",
      "Hilux",
      "Land Cruiser",
      "MR2",
      "Paseo",
      "Picnic",
      "Prius",
      "RAV4",
      "Sequoia",
      "Starlet",
      "Supra",
      "Tundra",
      "Urban Cruiser",
      "Verso",
      "Yaris",
      "Yaris Verso",
    ],
  },
  {
    make: "BMW",
    models: [
      "i3",
      "i8",
      "M3",
      "M4",
      "M5",
      "M6",
      "Rad 1",
      "Rad 2",
      "Rad 3",
      "Rad 4",
      "Rad 5",
      "Rad 6",
      "Rad 7",
      "Rad 8",
      "X1",
      "X3",
      "X4",
      "X5",
      "X6",
      "Z3",
      "Z4",
    ],
  },
  {
    make: "Buick",
    models: [
      "Cascada",
      "Encore",
      "Envision",
      "Regal",
      "Riviera",
      "Enclave",
      "Encore GX",
      "LaCrosse",
      "RendezVous",
      "Velite",
    ],
  },
  {
    make: "Geely",
    models: [
      "Atlas",
      "Emgrand 7",
      "FC (Vision)",
      "LC Cross",
      "SC7",
      "Atlas Pro",
      "Emgrand EC7",
      "MK",
      "Tugella",
      "CK",
      "Emgrand GT",
      "MK Cross",
      "Coolray",
      "Emgrand X7",
    ],
  },
  {
    make: "Lada",
    models: ["Priora", "Vesta", "Granta", "XRAY", "Kalina", "Largus"],
  },
  {
    make: "Volkswagen",
    models: [
      "Amarok",
      "Beetle",
      "Bora",
      "Caddy",
      "Life",
      "California",
      "Caravelle",
      "CC",
      "Crafter",
      "CrossTouran",
      "Eos",
      "Fox",
      "Golf",
      "Jetta",
      "LT",
      "Lupo",
      "Multivan",
      "New Beetle",
      "New Beetle Cabrio",
      "Passat",
      "Passat CC",
      "Phaeton",
      "Polo",
      "Scirocco",
      "Sharan",
      "T4",
      "T5",
      "Tiguan",
      "Touareg",
      "Touran",
    ],
  },
  {
    make: "Suzuki",
    models: [
      "Alto",
      "Baleno",
      "Baleno kombi",
      "Grand Vitara",
      "Grand Vitara XL-7",
      "Ignis",
      "Jimny",
      "Kizashi",
      "Liana",
      "Samurai",
      "Splash",
      "Swift",
      "SX4",
      "SX4 Sedan",
      "Vitara",
      "Wagon R+",
    ],
  },
  {
    make: "Mercedes-Benz",
    models: [
      "100 D",
      "115",
      "124",
      "126",
      "190",
      "190 D",
      "190 E",
      "200 - 300",
      "200 D",
      "200 E",
      "210 Van",
      "210 kombi",
      "310 Van",
      "310 kombi",
      "230 - 300 CE Coupe",
      "260 - 560 SE",
      "260 - 560 SEL",
      "500 - 600 SEC Coupe",
      "Trieda A",
      "A",
      "A L",
      "AMG GT",
      "Trieda B",
      "Trieda C",
      "C",
      "C Sportcoupe",
      "C T",
      "Citan",
      "CL",
      "CLA",
      "CLC",
      "CLK Cabrio",
      "CLK Coupe",
      "CLS",
      "Trieda E",
      "E",
      "Trieda G",
      "G Cabrio",
      "GL",
      "GLA",
      "GLC",
      "GLE",
      "GLK",
      "Trieda M",
      "MB 100",
      "Trieda R",
      "Trieda S",
      "S",
      "S Coupe",
      "SL",
      "SLC",
      "SLK",
      "SLR",
      "Sprinter",
    ],
  },
  {
    make: "Saab",
    models: ["9-3", "9-5", "900", "900 C", "900 C Turbo", "9000"],
  },
  {
    make: "Audi",
    models: [
      "100",
      "80",
      "90",
      "A1",
      "A2",
      "A3",
      "A4",
      "A5",
      "A6",
      "A7",
      "A8",
      "Q3",
      "Q5",
      "Q7",
      "R8",
      "RS5",
      "RS6 Avant",
      "RS7",
      "S3-S3 Sportback",
      "S4 Cabriolet",
      "S4-S4 Avant",
      "S5-S5 Cabriolet",
      "S6-RS6",
      "S7",
      "S8",
      "SQ5",
      "TT Coupe",
      "TT Roadster",
      "TTS",
    ],
  },
  {
    make: "Kia",
    models: [
      "Avella",
      "Besta",
      "Carens",
      "Carnival",
      "Ceed",
      "Cerato",
      "K 2500",
      "Magentis",
      "Opirus",
      "Optima",
      "Picanto",
      "Pregio",
      "Pride",
      "Pro Ceed",
      "Rio",
      "Sephia",
      "Shuma",
      "Sorento",
      "Soul",
      "Sportage",
      "Venga",
    ],
  },
  {
    make: "Land Rover",
    models: [
      "109",
      "Defender",
      "Discovery",
      "Discovery Sport",
      "Freelander",
      "Range Rover",
      "Range Rover Evoque",
      "Range Rover Sport",
    ],
  },
  {
    make: "Dodge",
    models: [
      "Avenger",
      "Caliber",
      "Challenger",
      "Charger",
      "Grand Caravan",
      "Journey",
      "Magnum",
      "Nitro",
      "RAM",
      "Stealth",
      "Viper",
    ],
  },
  {
    make: "Chrysler",
    models: [
      "300 C",
      "Crossfire",
      "Grand Voyager",
      "LHS",
      "Neon",
      "Pacifica",
      "Plymouth",
      "PT Cruiser",
      "Sebring",
      "Stratus",
      "Town & Country",
      "Voyager",
    ],
  },
  {
    make: "Ford",
    models: [
      "Aerostar",
      "B-Max",
      "C-Max",
      "Cortina",
      "Cougar",
      "Edge",
      "Escort",
      "Explorer",
      "F-150",
      "F-250",
      "Fiesta",
      "Focus",
      "Fusion",
      "Galaxy",
      "Grand C-Max",
      "Ka",
      "Kuga",
      "Maverick",
      "Mondeo",
      "Mondeo Combi",
      "Mustang",
      "Orion",
      "Puma",
      "Ranger",
      "S-Max",
      "Sierra",
      "Street Ka",
      "Tourneo Connect",
      "Tourneo Custom",
      "Transit",
      "Windstar",
    ],
  },
  { make: "Hummer", models: ["H2", "H3"] },
  {
    make: "Hyundai",
    models: [
      "Accent",
      "Atos",
      "Atos Prime",
      "Coupe",
      "Elantra",
      "Galloper",
      "Genesis",
      "Getz",
      "Grandeur",
      "H 350",
      "H1",
      "H200",
      "i10",
      "i20",
      "i30",
      "i40",
      "ix20",
      "ix35",
      "ix55",
      "Lantra",
      "Matrix",
      "Santa Fe",
      "Sonata",
      "Terracan",
      "Trajet",
      "Tucson",
      "Veloster",
    ],
  },
  { make: "Infiniti", models: ["EX", "FX", "G", "G Coupe", "M", "Q", "QX"] },
  {
    make: "Jaguar",
    models: [
      "Daimler",
      "F-Pace",
      "F-Type",
      "S-Type",
      "Sovereign",
      "X-Type",
      "XE",
      "XF",
      "XJ",
      "XJ12",
      "XJ6",
      "XJ8",
      "XJ8",
      "XJR",
      "XK",
      "XK8 Convertible",
      "XKR",
    ],
  },
  {
    make: "Jeep",
    models: [
      "Cherokee",
      "Commander",
      "Compass",
      "Grand Cherokee",
      "Patriot",
      "Renegade",
      "Wrangler",
    ],
  },
  {
    make: "Nissan",
    models: [
      "100 NX",
      "200 SX",
      "350 Z",
      "370 Z",
      "Almera",
      "Cabstar E - T",
      "Cabstar TL2 Valnik",
      "e-NV200",
      "GT-R",
      "Insterstar",
      "Juke",
      "King Cab",
      "Leaf",
      "Maxima",
      "Micra",
      "Murano",
      "Navara",
      "Note",
      "NP300 Pickup",
      "NV200",
      "NV400",
      "Pathfinder",
      "Patrol",
      "Patrol GR",
      "Pickup",
      "Pixo",
      "Primastar",
      "Primera",
      "Pulsar",
      "Qashqai",
      "Serena",
      "Sunny",
      "Terrano",
      "Tiida",
      "Trade",
      "Vanette Cargo",
      "X-Trail",
    ],
  },
  {
    make: "Volvo",
    models: [
      "240",
      "340",
      "360",
      "460",
      "850",
      "C30",
      "C70",
      "S40",
      "S60",
      "S70",
      "S80",
      "S90",
      "V40",
      "V50",
      "V60",
      "V70",
      "V90",
      "XC60",
      "XC70",
      "XC90",
    ],
  },
  {
    make: "Daewoo",
    models: [
      "Espero",
      "Kalos",
      "Lacetti",
      "Lanos",
      "Leganza",
      "Lublin",
      "Matiz",
      "Nexia",
      "Nubira",
      "Racer",
      "Tacuma",
      "Tico",
    ],
  },
  {
    make: "Fiat",
    models: [
      "1100",
      "126",
      "500",
      "500L",
      "500X",
      "850",
      "Barchetta",
      "Brava",
      "Cinquecento",
      "Coupe",
      "Croma",
      "Doblo",
      "Ducato",
      "Florino",
      "Freemont",
      "Grande Punto",
      "Idea",
      "Linea",
      "Marea",
      "Multipla",
      "Palio",
      "Panda",
      "Punto",
      "Qubo",
      "Scudo",
      "Sedici",
      "Seicento",
      "Stilo",
      "Strada",
      "Talento",
      "Tipo",
      "Ulysse",
      "Uno",
      "X-9",
    ],
  },
  {
    make: "MINI",
    models: [
      "Cooper",
      "Cooper Cabrio",
      "Cooper Clubman",
      "Cooper D",
      "Cooper S",
      "Countryman",
      "Mini One",
      "One D",
    ],
  },
  { make: "Rover", models: ["200", "214", "218", "25", "400", "414", "416", "620", "75"] },
  {
    make: "Smart",
    models: ["Cabrio", "City-Coupe", "Compact Pulse", "Forfour", "Fortwo", "Roadster"],
  },
];
