import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "styles/Home.module.scss";
import React from "react";
import Link from "next/link";
import { cars } from "constants/cars";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
          <ul>
            {cars
              .sort((a, b) => a.make.localeCompare(b.make))
              .map((car, index) => (
                <li key={index}>
                  <Link href={`/cars/${car.make}`}>
                    <a>{car.make}</a>
                  </Link>

                  {car.models && (
                    <ul>
                      {car.models.map((el, index) => (
                        <ul key={index}>
                          <li>
                            <Link href={`/cars/${car.make}/${el}`}>
                              <a>{el}</a>
                            </Link>
                          </li>
                        </ul>
                      ))}
                    </ul>
                  )}
                </li>
              ))}
          </ul>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    </>
  );
};

export default Home;
