import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import Link from "next/link";
import { cars } from "constants/cars";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>
        {cars
          .sort((a, b) => a.make.localeCompare(b.make))
          .map((car, index) => (
            <li key={index}>
              <Link href={`/cars/${car.make}`}>
                <a>{car.make}</a>
              </Link>

              {car.models && (
                <ul>
                  {car.models.map((el, index) => (
                    <li key={index}>
                      <Link href={`/cars/${car.make}/${el}`}>
                        <a>{el}</a>
                      </Link>
                    </li>
                  ))}
                </ul>
              )}
            </li>
          ))}
      </ul>
    </>
  );
};

export default Home;
